backend:
  name: git-gateway
  branch: main  # Pastikan sama dengan branch repo

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

publish_mode: editorial_workflow

collections:
  - name: "news"
    label: "Berita"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "html"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Gambar Utama", name: "thumbnail", widget: "image" }
      - { label: "Isi Berita", name: "body", widget: "markdown" }
